# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gz4MLHlBu4TN7puRUoZHgb08_PgevlQb
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Membaca data CSV dari URL
def load_data():
    # Load CSV data into a DataFrame
    data = pd.read_csv("PRSA_Data_Aotizhongxin_20130301-20170228.csv")

    # Convert 'year', 'month', 'day', and 'hour' columns to datetime
    data['tanggal'] = pd.to_datetime(data[['year', 'month', 'day', 'hour']])

    return data

data = load_data()

# Menampilkan judul dashboard
st.title('Dashboard Polusi Udara Aotizhongxin')

# Menampilkan visualisasi untuk Pertanyaan 1
st.subheader('Tren Kadar PM2.5 di Aotizhongxin (2013-2017)')
data_aotizhongxin = data[data['station'] == 'Aotizhongxin']
pm25_tahunan = data_aotizhongxin.set_index('tanggal')['PM2.5'].resample('Y').mean()
fig1, ax1 = plt.subplots()
pm25_tahunan.plot(ax=ax1, marker='o')
ax1.set_xlabel('Tahun')
ax1.set_ylabel('Rata-rata PM2.5 (µg/m³)')
st.pyplot(fig1)

# Menampilkan visualisasi untuk Pertanyaan 2
st.subheader('Pola Harian Kadar CO di Aotizhongxin (2017)')
data_aotizhongxin_2017 = data[(data['station'] == 'Aotizhongxin') & (data['tanggal'].dt.year == 2017)]
co_per_jam = data_aotizhongxin_2017.groupby(data_aotizhongxin_2017['tanggal'].dt.hour)['CO'].mean()
fig2, ax2 = plt.subplots()
co_per_jam.plot(ax=ax2, kind='bar', color='skyblue')
ax2.set_xlabel('Jam (24-jam)')
ax2.set_ylabel('Rata-rata CO (mg/m³)')
st.pyplot(fig2)